name: 'request-republish-package'
description: 'Upload a package as a GitHub Artifact, then log a particular message which is observed by a workflow in another repo which will pick up the artifact and republish it.'
inputs:
  package-path:
    description: 'The path to the package file, can include globs.'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
